default_job = "run-check"
env.CARGO_TERM_COLOR = "always"

[jobs.run-check]
command = ["cargo", "check"]
need_stdout = true
on_success = "job:run-test"

[jobs.run-test]
command = ["cargo", "test"]
need_stdout = true
on_success = "job:run-proper"

[jobs.run-proper]
command = ["cargo", "run"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[keybindings]
r = "job:run-check"
