name: Security audit
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
jobs:
  rust_security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install cargo-deny
        uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: |
          cd apps/api
          cargo deny check advisories
